version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: library/fastapi-blocklist:latest  # Specify the custom image name and tag
    container_name: fastapi-blocklist
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
