version: '3.8'

services:
  ipchecking-service:
    build:
      context: ./ipchecking
      dockerfile: Dockerfile
    image: ipchecking:latest  # Specify the custom image name and tag
    container_name: ipchecking
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  blocklistupdater-service:
    build:
      context: ./blocklistupdater
      dockerfile: Dockerfile
    image: blocklistupdater:latest
    container_name: blocklistupdater
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
