apiVersion: apps/v1
kind: Deployment
metadata:
  name: blocklistupdater
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blocklistupdater
  template:
    metadata:
      labels:
        app: blocklistupdater
    spec:
      containers:
      - name: blocklistupdater
        image: blocklistupdater:latest
        imagePullPolicy: Never  # Use the local image
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
