apiVersion: apps/v1
kind: Deployment
metadata:
  name: blocklist-updater
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blocklist-updater
  template:
    metadata:
      labels:
        app: blocklist-updater
    spec:
      containers:
      - name: blocklist-updater
        image: blocklist-updater:latest
        imagePullPolicy: Never  # Use the local image
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
