apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipchecking
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ipchecking
  template:
    metadata:
      labels:
        app: ipchecking
    spec:
      containers:
      - name: ipchecking
        image: ipchecking:latest
        imagePullPolicy: Never  # Use the local image
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
